cores: exe_cores.c
	gcc -Wall exe_cores.c xdraw.c ximage.c xmath.c xpng.c xy.c -o exe_cores
	./exe_cores
texto: exe_texto.c
	gcc -Wall exe_texto.c xdraw.c ximage.c xmath.c xpng.c xy.c -o exe_texto
	./exe_texto
