
all:

# %: %.c
# 	gcc -Wall $@.c color.c xmath.c base.c lodepng.c draw.c text.c modules.c -o $@
# 	./$@

%: %.cpp
	g++ -Wall $@.cpp color.c xmath.c base.c lodepng.c draw.c text.c modules.c -o $@
	./$@