
all:

# %: %.c
# 	gcc -Wall $@.c color.c xmath.c base.c lodepng.c draw.c text.c modules.c -o $@
# 	./$@

%: %.cpp
	gcc -Wall $@.cpp color.c xmath.c base.c lodepng.c draw.c text.c modules.c -o $@
	./$@

# gcc -Wall -Wextra -Werror -fsanitize=address $@.cpp color.c xmath.c base.c lodepng.c draw.c text.c modules.c -o $@
#	./$@
